SELECT
    AD_ID,
    CODUSULIB,
    SUM(CASE WHEN CAST(DHLIB AS DATE) = CAST(GETDATE() AS DATE) THEN VLRLIBERADO ELSE 0 END) VLRLIBERADODIA,
    SUM(VLRLIBERADO) VLRLIBERADOMES
FROM TSILIB LIB
WHERE AD_ID = 2
  AND FORMAT(CAST(DHLIB AS DATE), 'MM/yyyy') = FORMAT(CAST(GETDATE() AS DATE),'MM/yyyy')
GROUP BY
    AD_ID,
    CODUSULIB
