WITH T1 AS (SELECT
    CAB.NUNOTA,
    ISNULL(LIB.CODUSU,GAL.CODUSU) CODUSU,
    CASE
        WHEN LIBP.ID IS NOT NULL THEN 'Liberacao por Produto'
        WHEN LIBV.ID IS NOT NULL THEN 'Liberacao por Comprador'
        WHEN LIBG.ID IS NOT NULL THEN 'Liberacao por Grupo de Produto'
        WHEN LIBS.ID IS NOT NULL THEN 'Liberacao por Sub Grupo de Produto'
        WHEN LIBF.ID IS NOT NULL THEN 'Liberacao por Fornecedor'
        WHEN LIBE.ID IS NOT NULL THEN 'Liberacao por Empresa'
        WHEN LIBC.ID IS NOT NULL THEN 'Liberacao por Centro de Resultado'
        ELSE 'Sem Regra de Liberacao' END OBS,
    CASE
        WHEN LIBP.ID IS NOT NULL THEN 'TGFITE'
        WHEN LIBV.ID IS NOT NULL THEN 'TGFCAB'
        WHEN LIBG.ID IS NOT NULL THEN 'TGFITE'
        WHEN LIBS.ID IS NOT NULL THEN 'TGFITE'
        WHEN LIBF.ID IS NOT NULL THEN 'TGFCAB'
        WHEN LIBE.ID IS NOT NULL THEN 'TGFCAB'
        WHEN LIBC.ID IS NOT NULL THEN 'TGFCAB'
        ELSE 'TGFCAB' END TABELA,
    CASE
        WHEN LIBP.ID IS NOT NULL THEN ITE.SEQUENCIA
        WHEN LIBV.ID IS NOT NULL THEN 0
        WHEN LIBG.ID IS NOT NULL THEN ITE.SEQUENCIA
        WHEN LIBS.ID IS NOT NULL THEN ITE.SEQUENCIA
        WHEN LIBF.ID IS NOT NULL THEN 0
        WHEN LIBE.ID IS NOT NULL THEN 0
        WHEN LIBC.ID IS NOT NULL THEN 0
        ELSE 0 END SEQUENCIA,
    SUM(CASE
        WHEN LIBP.ID IS NOT NULL THEN ITE.VLRTOT
        WHEN LIBV.ID IS NOT NULL THEN CAB.VLRNOTA
        WHEN LIBG.ID IS NOT NULL THEN ITE.VLRTOT
        WHEN LIBS.ID IS NOT NULL THEN ITE.VLRTOT
        WHEN LIBF.ID IS NOT NULL THEN CAB.VLRNOTA
        WHEN LIBE.ID IS NOT NULL THEN CAB.VLRNOTA
        WHEN LIBC.ID IS NOT NULL THEN CAB.VLRNOTA
        ELSE CAB.VLRNOTA END) VLRTOT,
    LIB.ID
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
INNER JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
INNER JOIN TGFGRU GRU ON GRU.CODGRUPOPROD = PRO.CODGRUPOPROD
LEFT JOIN AD_LIBLIM LIBP ON LIBP.CODPROD = ITE.CODPROD AND LIBP.VALIDADE > GETDATE()
LEFT JOIN AD_LIBLIM LIBV ON LIBV.CODVEND = CAB.CODVEND AND LIBV.VALIDADE > GETDATE()
LEFT JOIN AD_LIBLIM LIBG ON LIBG.CODGRUPOPROD = PRO.CODGRUPOPROD AND LIBG.VALIDADE > GETDATE()
LEFT JOIN AD_LIBLIM LIBS ON LIBS.CODSUBGRUPO = GRU.CODGRUPAI AND LIBS.VALIDADE > GETDATE()
LEFT JOIN AD_LIBLIM LIBF ON LIBF.CODPARC = CAB.CODPARC AND LIBF.VALIDADE > GETDATE()
LEFT JOIN AD_LIBLIM LIBE ON LIBE.CODEMP = CAB.CODEMP AND LIBE.VALIDADE > GETDATE()
LEFT JOIN AD_LIBLIM LIBC ON LIBC.CODCENCUS = CAB.CODCENCUS AND LIBC.VALIDADE > GETDATE()
LEFT JOIN AD_LIBLIM LIB ON LIB.ID = ISNULL(LIBP.ID,ISNULL(LIBV.ID,ISNULL(LIBG.ID,ISNULL(LIBS.ID,ISNULL(LIBF.ID,ISNULL(LIBE.ID,LIBC.ID))))))
LEFT JOIN AD_GRUALC GAL ON GAL.ID = ISNULL(LIBP.ID,ISNULL(LIBV.ID,ISNULL(LIBG.ID,ISNULL(LIBS.ID,ISNULL(LIBF.ID,ISNULL(LIBE.ID,LIBC.ID))))))
WHERE CAB.NUNOTA = :NUNOTA
GROUP BY CAB.NUNOTA,
    ISNULL(LIB.CODUSU,GAL.CODUSU),
    CASE
        WHEN LIBP.ID IS NOT NULL THEN 'Liberacao por Produto'
        WHEN LIBV.ID IS NOT NULL THEN 'Liberacao por Comprador'
        WHEN LIBG.ID IS NOT NULL THEN 'Liberacao por Grupo de Produto'
        WHEN LIBS.ID IS NOT NULL THEN 'Liberacao por Sub Grupo de Produto'
        WHEN LIBF.ID IS NOT NULL THEN 'Liberacao por Fornecedor'
        WHEN LIBE.ID IS NOT NULL THEN 'Liberacao por Empresa'
        WHEN LIBC.ID IS NOT NULL THEN 'Liberacao por Centro de Resultado'
        ELSE 'Sem Regra de Liberacao' END,
    CASE
        WHEN LIBP.ID IS NOT NULL THEN 'TGFITE'
        WHEN LIBV.ID IS NOT NULL THEN 'TGFCAB'
        WHEN LIBG.ID IS NOT NULL THEN 'TGFITE'
        WHEN LIBS.ID IS NOT NULL THEN 'TGFITE'
        WHEN LIBF.ID IS NOT NULL THEN 'TGFCAB'
        WHEN LIBE.ID IS NOT NULL THEN 'TGFCAB'
        WHEN LIBC.ID IS NOT NULL THEN 'TGFCAB'
        ELSE 'TGFCAB' END,
    CASE
        WHEN LIBP.ID IS NOT NULL THEN ITE.SEQUENCIA
        WHEN LIBV.ID IS NOT NULL THEN 0
        WHEN LIBG.ID IS NOT NULL THEN ITE.SEQUENCIA
        WHEN LIBS.ID IS NOT NULL THEN ITE.SEQUENCIA
        WHEN LIBF.ID IS NOT NULL THEN 0
        WHEN LIBE.ID IS NOT NULL THEN 0
        WHEN LIBC.ID IS NOT NULL THEN 0
        ELSE 0 END,
    LIB.ID)
SELECT
    CODUSU,
    OBS,
    TABELA,
    SEQUENCIA,
    VLRTOT,
    ROW_NUMBER() OVER (PARTITION BY NUNOTA,SEQUENCIA ORDER BY NUNOTA,SEQUENCIA) SEQCASCATA,
    ID
FROM T1
WHERE ID IS NOT NULL


/*
Material (Produto), - LIBP
Cód. Comprador, - LIBV
Grupo, - LIBG
Subgrupo, - LIBS
Fornecedor, - LIBF
Unidade de Negócio(Empresa) - LIBE
 Centro de Resultado. - LIBC
*/